### ISSUE TITLE
Importing twice the same source with brace arrays is not working as expected

### ISSUE THREAD

**Issue by mtabacman** [instantiations/tonel-vast#57] opened 2020-09-17 19:59 UTC
- Using VAST 9.2.2
- Download Buoy v6.0.0 (https://github.com/ba-st/Buoy/releases/tag/v6.0.0) to DIR-BUOY
- Execute:
```
(TonelLoader readFromPath: (CfsPath named: DIR-BUOY)) 
	beUnattended;
	useSpecifiedVersion: 'v6.0.0 -  93e12ea';
	loadApplicationsForPackagesNamed: #('Buoy-Assertions' 'Buoy-Collections')
```
This completes as expected, with many methods that include brace arrays commented because they wouldn't compile in VAST 9.2.2.

- Execute the script again.
-- Expected: new application editions spawned from the previous ones with no changes in the classes
-- Obtained: debugger complaining that the method did not compile

**Comment by eMaringolo** [comment] 2020-09-17 21:20
The issue is that Buoy is defining `Error>>signal:` with a source that fails to compile (because of the curly braces syntax).
The next time it tries to parse the error, an exception is signalled (`TonelParseError`) and it's inheriting the `Error>>signal:` that failed to compile. So instead of signalling the error, is notifying that the method failed to compile.

Bottom line: It is not that it is failing to compile something during the load, it is notifying that you're using a method that failed to compile. 

Fix: You either remove that method from Buoy or change its source syntax.

**Comment by gcotelli** [comment] 2020-09-18 23:16
Or we can wait until the new release of VA including the brace array syntax :)

**Comment by eMaringolo** [comment] 2020-10-07 21:05
Closing this because it wasn't a Tonel issue.

**Closed by eMaringolo** 2020-10-07 21:05 UTC
