### ISSUE TITLE
Importing Boardwalk v6 duplicates categories for exiting methods

### ISSUE THREAD

**Issue by mtabacman** [instantiations/tonel-vast#70] opened 2021-02-24 18:53 UTC
- Starting on a VAST 9.2.2 image.
- [Boardwalk v5.1.1](https://github.com/ba-st/Boardwalk/releases/tag/v5.1.1) has been imported previously using Tonel Configuration Map 1.65.
- Loaded Tonel Configuration Map 1.74
- The current versions of all applications involved are not the ones imported but direct descendants of them with only minor changes.
- Attempted to import [Boardwalk v6.0.0](https://github.com/ba-st/Boardwalk/releases/tag/v6.0.0) by executing the following script:
```
(TonelLoader readFromPath: (CfsPath named: 'LOCALPATH')) 
	beUnattended;
	useSpecifiedVersion: 'v6.0.0 - 261dbed';
	loadApplicationsForPackagesNamed: #(
'Boardwalk'
'Boardwalk-SUnit'
'Boardwalk-Tests'
)
```
- This ends up with the correct method changes in the image, but also all the existing categories for methods that did not change are created again and left empty.

**Comment by eMaringolo** [comment] 2021-02-25 15:49
I could reproduce the situation and find why you're getting duplicates.

The Loader loads the method categories "as is" in the Tonel file, which in the case of a file coming from Pharo it is a symbol object for the category name. The first time, the category gets defined as a Symbol, but once stored in the ENVY Library it gets converted to a String. Next time you load the class, it will load the method categories as Strings.

When you load the application again from a Tonel format, the class will have the `'accessing'` category name, but you will also be loading the `#accessing` category name, so the loaded method will have both a String and a Symbol with the same "name".

If you export from VAST to Tonel, the method category will be properly exported as a String, following the not-yet canonicalized "1.0 spec" of Tonel, so when you go export/import using VAST you don't find such issues.

The workaround is to convert all categories to String upon reading them, basically modifying this method:
```smalltalk
TonelReaderMethodDefinition>>#className: nameString classSide: aBoolean categories: aCollection stamp: stampString

	^self new
		initializeClassName: nameString
		classSide: aBoolean
		categories: (aCollection collect: [:each | each asString]) "<-- this modification"
		stamp: stampString;
		yourself
		
```

When exporting it is a little trickier, because there is no convention on which format to use when serializing category names.
E.g. The 1.0 spec draft specifies strings, VAST uses strings, but Pharo uses symbols. Maybe this should be a setting in the TonelWriter, until the 1.0 spec is established.

**Comment by mtabacman** [comment] 2021-02-26 11:12
The fix works perfectly. Thanks!

**Comment by marianopeck** [comment] 2021-07-07 12:41
@eMaringolo didn't we fix this recently? Should we close it?

**Closed** 2021-07-07 12:50 UTC
Labels: importing, portability
