### ISSUE TITLE
AbtShelProgramStarterUnixPlatformSubApp missing

### ISSUE THREAD

**Issue by HeSe** [instantiations/tonel-vast#54] opened 2020-06-20 23:50 UTC
Tonel can currently not be loaded into a Unix environment because a AbtShellProgramStarter specific to Unix  is missing. (an implementation of AbtShelProgramStarterUnixPlatformSubApp is missing).
For Windows there is a AbtShelProgramStarterWindowsPlatformSubApp available.

**Comment by marianopeck** [comment] 2020-10-30 20:51
Maybe a duplicate of #60 ?

**Closed** 2020-11-12 15:52 UTC
